apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api
  labels:
    app: coordinates-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coordinates-api
  
  template:
    metadata:
      labels:
        app: coordinates-api
    spec:
      containers:
      - name: api
        image: mattiyeshurun/coordinates_api:v1
        
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          value: "postgres-0.postgres-svc"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "coordinates_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          
